Added Contact Us Page
CodeHarborHub/codeharborhub pull request #195
Opened 2024-05-22 14:09 UTC by Hemashree21

I added the UI for the Contact Us page and it's responsive as well.

![image](https://github.com/CodeHarborHub/codeharborhub/assets/138188163/d2a07bf4-bb90-411e-a351-e01a3837230d)

@Ajay-Dhangar please check and let me know if any changes are required

2024-05-22 15:32 UTC, Ajay-Dhangar requested changes
Now Change code based on suggestions

2024-05-22 15:32 UTC, Ajay-Dhangar commented on src/pages/contact/index.tsx
> +const Index = () => {
you can use or replace `Contact` to `Index`

2024-05-22 15:32 UTC, Ajay-Dhangar commented on src/pages/contact/index.tsx
> +export default Index;
you can use or replace `Contact` to `Index`

2024-05-22 15:32 UTC, Ajay-Dhangar commented on src/pages/contact/styles.module.css
> +.myform {
use grid for layout for good responsive design

2024-05-22 15:32 UTC, Ajay-Dhangar commented on src/pages/contact/styles.module.css
> +.myform {
Because something is not working 

![image](https://github.com/CodeHarborHub/codeharborhub/assets/99037494/8a2abb25-fbd2-4ac2-abdf-252461d42215)

2024-05-23 07:36 UTC, Ajay-Dhangar approved these changes
Done

2024-05-23 07:36 UTC, merged

2024-05-23 08:44 UTC, Hemashree21 commented
Thankyou