Added animation
CodeHarborHub/codeharborhub pull request #252
Opened 2024-05-26 10:52 UTC by harshmishra19

## Related Issue

This PR fixes #250 

## Description

I have added the animation

## Type of PR

- [ ] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub/assets/115486960/55cc416e-2501-458c-bf66-4e1ec8f2c87a

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [ x] I have performed a self-review of my code.
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-05-26 15:12 UTC, Ajay-Dhangar requested changes
please checkout and apply best practice rules

**So, Now resolve all**

- [ ] [Unexpected var, use let or const instead](https://app.deepsource.com/gh/CodeHarborHub/codeharborhub/run/4f9d43dc-1e65-4a27-bce9-82e75d32baa0/javascript/JS-0239?listindex=0)
- [ ] [Should not have unused variables](https://app.deepsource.com/gh/CodeHarborHub/codeharborhub/run/4f9d43dc-1e65-4a27-bce9-82e75d32baa0/javascript/JS-0128?listindex=1)
- [ ] [Use shorthand property syntax for object literals](https://app.deepsource.com/gh/CodeHarborHub/codeharborhub/run/4f9d43dc-1e65-4a27-bce9-82e75d32baa0/javascript/JS-0240?listindex=2)
- [ ][ Logical operator can be refactored to optional chain](https://app.deepsource.com/gh/CodeHarborHub/codeharborhub/run/4f9d43dc-1e65-4a27-bce9-82e75d32baa0/javascript/JS-W1044?listindex=12)
- [ ] [more](https://app.deepsource.com/gh/CodeHarborHub/codeharborhub/run/4f9d43dc-1e65-4a27-bce9-82e75d32baa0/javascript?page=1)

2024-05-26 15:12 UTC, Ajay-Dhangar commented on src/components/HomePage/vanilla-tilt.js
> +var VanillaTilt = (function () {
You can try `const` and `let` not good practice for using in js `var` keyword

2024-05-26 15:14 UTC, Ajay-Dhangar commented
Good work, only debug some code and make good code for us.

2024-05-27 06:04 UTC, Ajay-Dhangar approved these changes
Now, I merged in this time and next time you try to follow best practice rules.

2024-05-27 06:04 UTC, merged

2024-05-27 06:17 UTC, harshmishra19 commented
YESS!!!!