NextJs docs has been added
CodeHarborHub/codeharborhub pull request #360
Opened 2024-06-02 12:35 UTC by Aksshay88

## Related Issue

#359 

## Description

I have added the Next js docs from the scratch where user could see from the first how to download the Nextjs and app routing ,page routing , architecture 

## Type of PR

- [X] Feature enhancement

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]
![image](https://github.com/CodeHarborHub/codeharborhub/assets/119944779/a09d4b3e-3433-4e0f-881b-8ad7e76596c3)
![image](https://github.com/CodeHarborHub/codeharborhub/assets/119944779/27806fe7-8a31-402b-940a-93b828393631)

## Checklist

- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)
- [NextJs Documetation](https://nextjs.org/docs) 

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-02 12:37 UTC, Aksshay88 commented
Pls do add the GSSOC Label

2024-06-02 12:48 UTC, Ajay-Dhangar requested changes
Make Sure, You follow our structure

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)
- [NextJs Documetation](https://nextjs.org/docs) 

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-02 12:48 UTC, Ajay-Dhangar commented on docs/NextJs/_category_.json
> +    "position": 8,
`"position": 8,`   already define you can try to put other `position`

2024-06-02 12:48 UTC, Ajay-Dhangar commented on docs/NextJs/index.md
> +<div align=center>
use on top

```md
---
id: ____
title: ____
sidebar_label: ____
sidebar_position: ____
tags: [ ____, ____ ]
description: ____
---
```

2024-06-02 13:02 UTC, Aksshay88 commented
@Ajay-Dhangar Sorry For making it a mistake Now I resolved the changes you have mentioned .You could check it now .Thanks in advance.

2024-06-02 14:20 UTC, Aksshay88 reviewed
I have changed the suggestion you have asked for .Thanks in advance.Happy Hacking

2024-06-02 14:29 UTC, Aksshay88 commented
@Ajay-Dhangar  Just now saw what the problem is that docker cli is not identifying my image from the format of webp

Now I have added it in a local format where it could identify the image and it could run without error 

I request you to run it again or review the changes I have made.Thank you

2024-06-02 14:32 UTC, Ajay-Dhangar requested changes
change for best practice

2024-06-02 14:32 UTC, Ajay-Dhangar commented on docs/NextJs/index.md
> +id: Next JS
id put like `next-js`

2024-06-02 14:32 UTC, Ajay-Dhangar commented on docs/NextJs/index.md
> +id: Next JS
id put like `next-js`

2024-06-02 14:32 UTC, Ajay-Dhangar commented on docs/NextJs/index.md
> +<a href="https://nextjs.org/docs/app"><img src="https://github.com/Aksshay88/Macbook/assets/119944779/1c389169-463a-42e1-b4f0-28830ed4b8a8"></a>
**Bad Practice:**

```md
<img src="img.png">
```

**Good Practice:**

```md
<img src="img.png" alt="Image name" />
```

2024-06-02 14:38 UTC, Aksshay88 commented
@Ajay-Dhangar sure will change it and get back to ASAP

Thanks in advance

2024-06-02 15:55 UTC, Ajay-Dhangar requested changes
Everything is fine. Please focus on XML/JSX syntax best practices.

2024-06-02 15:55 UTC, Ajay-Dhangar commented on docs/NextJs/index.md
> +Create a root layout inside `app/layout.tsx` with the required `<html>` and ``<body>`` tags:
**Bade Practice:**

```md
``<body>``
```

**Good Practice:**

```md
`<body>`
```

2024-06-02 15:55 UTC, Ajay-Dhangar commented on docs/NextJs/index.md
> +<a href="https://nextjs.org/docs/app"><img src="emty.png"></a>
**Bad Practice:**

```md
<img src="empty.png">
```

**Good Practice:**

```md
<img src="empty.png" />
```

In JSX, all tags must be self-closing, so it's important to add the closing slash to the `<img>` tag.

2024-06-03 05:13 UTC, Aksshay88 commented
@Ajay-Dhangar Completed changing it .I hope your suggestion that you have requested has been rectified and thanks in advance .

2024-06-03 06:52 UTC, Ajay-Dhangar approved these changes
Done and fixed issues but content is not good so, next time write more better.

2024-06-03 06:56 UTC, merged

2024-06-03 06:57 UTC, Aksshay88 commented
@Ajay-Dhangar Sure Next time will write the content in a detailed manner