Solution next happy number added
CodeHarborHub/codeharborhub pull request #431
Opened 2024-06-03 16:09 UTC by Vipullakum007

## Related Issue

i want to add solution of "next happy number " problem https://github.com/CodeHarborHub/codeharborhub/issues/389
fixes : https://github.com/CodeHarborHub/codeharborhub/issues/389

## Description

i have added solution of "next happy number " problem

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub/assets/127659443/484cb717-080a-46b1-a8fe-1e9ed987ad00

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-03 16:36 UTC, Ajay-Dhangar requested changes
now remove code based on suggestions

2024-06-03 16:36 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0004-fibbonacci-sum.md
> +<<<<<<<<< Temporary merge branch 1
remove 

```md
<<<<<<<<< Temporary merge branch 1

=========
>>>>>>>>> Temporary merge branch 2
```

2024-06-03 16:55 UTC, Vipullakum007 commented
hey @Ajay-Dhangar , updated as per your suggestion you can merge it

2024-06-03 16:56 UTC, Ajay-Dhangar approved these changes
Done

2024-06-03 16:58 UTC, merged

2024-06-04 03:33 UTC, Vipullakum007 commented
hey @Ajay-Dhangar  , you add level3  easy problem "How many X's " , "Remove Duplicate" , then why level 2  by  @manishh12  for "my meduim problems can you make level3.